### ISSUE TITLE
Cannot open LAS: must either be for a block or all of DB

### ISSUE THREAD

**Issue by a-ludi** [thegenemyers/DAVIEWER#4]
When I try to open a LAS file with the latest DaViewer I get:

> LAS file assembly-reference.reads-simulated-pb.las must either be for a block or all of DB !

The file references two DBs and is the result of running `LAmerge` on (all) the block-level alignments. So, in theory, it should match the "all of DB" case.

**Comment by thegenemyers** [comment]
Fixed.  Gene
